version: '3'

volumes:
  nextcloud:
  db:

services

  db:
    image: mariadb
    # Environment file path.
    env_file: ./env/db.env
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ~/docker-nextcloud/db:/var/lib/mysql

  app:
    image: nextcloud:fpm
    # Environment file path.
    env_file: ./env/app.env
    restart: always
    links:
      - db
    volumes:
      - ~/docker-nextcloud/nextcloud:/var/www/html

  web:
    image: nginx
    restart: always
    ports:
      - ${PORT}:80
    links:
      - app
    volumes:
      - ~/docker-nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
