version: '3'
services:
  nextcloud:
    # Download Nextcloud image.
    image: nextcloud:${NEXTCLOUD_VERSION}
    # Environment file path.
    env_file: ./env/nextcloud.env
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
